#!/bin/sh
export RazorLoc=/data/mpierini/SEARCHES/RAZOR/Trees
export DYJetsToLL_files='/data/mpierini/SEARCHES/RAZOR/Trees/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola_MR150.0_R0.15_Ele.root /data/mpierini/SEARCHES/RAZOR/Trees/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola_MR150.0_R0.15_EleEle.root /data/mpierini/SEARCHES/RAZOR/Trees/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola_MR150.0_R0.15_Had.root /data/mpierini/SEARCHES/RAZOR/Trees/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola_MR150.0_R0.15_Mu.root /data/mpierini/SEARCHES/RAZOR/Trees/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola_MR150.0_R0.15_MuMu.root'
export WJetsToLNu_files='/data/mpierini/SEARCHES/RAZOR/Trees/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Ele.root /data/mpierini/SEARCHES/RAZOR/Trees/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Had.root /data/mpierini/SEARCHES/RAZOR/Trees/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Mu.root /data/mpierini/SEARCHES/RAZOR/Trees/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_MuMu.root'
export ZinvisibleJets_files='/data/mpierini/SEARCHES/RAZOR/Trees/ZinvisibleJets_7TeV-madgraph_MR150.0_R0.15_Had.root'
export TTJets_files='/data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Ele.root /data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_EleEle.root /data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Had.root /data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_Mu.root /data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_MuEle.root /data/mpierini/SEARCHES/RAZOR/Trees/TTJets_TuneZ2_7TeV-madgraph-tauola_MR150.0_R0.15_MuMu.root'

python scripts/runAnalysis.py -a TwoDFit -c config/TwoDTailFit_DYJetsToLL_MR150.0_R0.15.cfg -o DYJetsToLL_razor_MR150.0_R0.15.root $DYJetsToLL_files
python scripts/runAnalysis.py -a TwoDFit -c config/TwoDTailFit_WJetsToLNu_MR150.0_R0.15.cfg -o WJetsToLNu_razor_MR150.0_R0.15.root $WJetsToLNu_files
python scripts/runAnalysis.py -a TwoDFit -c config/TwoDTailFit_TTJets_MR150.0_R0.15.cfg -o TTJets_razor_MR150.0_R0.15.root $TTJets_files
python scripts/runAnalysis.py -a TwoDFit -c config/TwoDTailFit_ZinvisibleJets_MR150.0_R0.15.cfg -o ZinvisibleJets_razor_MR150.0_R0.15.root $ZinvisibleJets_files