import sys
import os

def Binning(Box, noBtag):
    if Box == "TauTau" or Box == "Had":    
        MRbins = [400.0, 450.0, 500.0, 550.0, 600.0, 650.0, 700.0, 800, 900, 1000, 1200, 1600, 2000, 2600, 4500.0]
        if noBtag == False: Rsqbins = [0.18, 0.21, 0.24, 0.27, 0.3, 0.35, 0.4, 0.5, 0.65, 0.80, 1.5]
        else: Rsqbins = [0.18, 0.21, 0.24, 0.27, 0.3, 0.35, 0.4, 0.5]
    else:
        MRbins = [350, 410, 480, 560, 650, 750, 860, 980, 1200, 1600, 2500, 4500]
        if noBtag == True: Rsqbins = [0.11,0.15,0.2,0.25,0.30,0.35,0.40,0.45,0.50]
        else: Rsqbins = [0.11,0.15,0.2,0.25,0.30,0.35,0.40,0.45,0.50,0.56,0.62,0.70,0.80,1.5]
    return MRbins, Rsqbins

if __name__ == '__main__':

    if len(sys.argv) < 4:
        print "\nRun the script as follows:\n"
        print "python scripts/makeBluePlot.py BoxName ToyDir DataFile OutDir"
        print "with:"
        print "- BoxName = name of the Box (MuMu, MuEle, etc)"
        print "- ToyDir = directory with the .txt files generated by the fit"
        print "- DataFile = name of the corresponding data file"
        print "- OutDir = name of the output directory"
        print ""
        print "After the inputs you can specify the following options"
        print " --plotOnly  Run the plot-making macro from already computed bkg predictions"
        print " --noBtag    this is a 0btag box (i.e. R2 stops at 0.5)"
        sys.exit() 
    else:
        Box = sys.argv[1]
        ToyDir = sys.argv[2]
        Data = sys.argv[3]
        Label = sys.argv[4]
        noBtag = ""
        plotOnly = False
        for i in range(5,len(sys.argv)):
            if sys.argv[i] == "--noBtag": noBtag = "--noBtag"
            if sys.argv[i] == "--plotOnly": plotOnly = True

    if not plotOnly:
        os.system("python scripts/convertToyToROOT.py %s/frtoydata_%s" %(ToyDir, Box))
        os.system("python scripts/expectedYield_sigbin.py 1 expected_sigbin_%s.root %s %s/frtoydata_%s_*root"%(Box, Box, ToyDir, Box))
        os.system("python scripts/makeToyPVALUE_sigbin.py %s expected_sigbin_%s.root %s %s"%(Box, Box, Data, noBtag))
        os.system("mkdir %s"%(Label))
        os.system("mv nSigma_%s.* pvalue_sigbin_%s.* pvalue_%s.root expected_sigbin_%s.root table_%s.tex %s"%(Box, Box, Box, Box, Box, Label))
    else:
        os.system("rm %s/pvalue_%s.root" %(Label,Box))
        os.system("python scripts/makeToyPVALUE_sigbin.py %s %s/expected_sigbin_%s.root %s %s"%(Box, Label, Box, Data, noBtag))
        os.system("mv nSigma_%s.* pvalue_sigbin_%s.* pvalue_%s.root table_%s.tex %s"%(Box,Box, Box, Box, Label))

    # compile the latex table
    os.system("cd %s; pdflatex table_%s.tex" %(Label, Box))
